core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('',views.IndexView.as_view(), name="home"),
    path('add/',views.AddView.as_view(), name="add"),
    path('posts/',views.PostsView.as_view(), name="post"),
    path('<slug:slug>/', views.SingleView.as_view(), name="single"),
    path('edit/<int:pk>/', views.EditView.as_view(), name="edit"),
    path('delete/<int:pk>/', views.DeleteView.as_view(), name="delete")
]

myclassv/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include("core.urls")),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

class Core(models.Model):
    title = models.CharField(max_length=200)
    excerpt = models.TextField(null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='core')
    slug = models.SlugField(max_length=100, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('core:single', args=[self.slug])
    class Meta:
        ordering = ['-created']
    
    def __str__(self):
        return self.title


# Create your models here.

core/forms.py
from django import forms
from .models import Core

class  PostForm(forms.ModelForm):
    class Meta:
        model = Core
        fields = "__all__"

core/views.py
from django.shortcuts import render
from .models import*
from django.views.generic import ListView, DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from . forms import PostForm

# Create your views here. 
class IndexView(ListView):
    model = Core
    template_name = 'core/index.html'
    context_object_name = 'index'

class SingleView(DetailView):
    model = Core
    template_name = 'core/single.html'
    context_object_name = 'post'

class PostsView(ListView):
    model = Core
    template_name = 'core/posts.html'
    context_object_name = 'post_list'


class AddView(CreateView):
    model = Core
    template_name = 'core/add.html'
    fields = '__all__'
    success_url = reverse_lazy('core:post')


class EditView(UpdateView):
    model = Core
    template_name = 'core/edit.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:post')

class DeleteView(DeleteView):
    model = Core
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:post')
    template_name = 'core/confirm_delete.html'
    

core/templates/core/add.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container p-5">
    <form method="POST" novalidate> <!-- Change action="POST" to method="POST" -->
        {% csrf_token %}
        {% for field in form.visible_fields %} <!-- Correct typo here -->
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %} <!-- Correct typo here -->
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}

        <div class="form-group">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span> Add
            </button>
            <a class="btn btn-default" href="{% url 'core:post' %}">Cancel</a> <!-- Make sure this URL name is correct -->
        </div>
    </form>
</div>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>my class based views</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    </head>

    <body>
        {% include 'core/navbar.html' %}

        {% block content %}

        {% endblock %}
        
        <!-- Include jQuery from Google's CDN -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    </body>
</html>

core/templates/core/confirm_delete.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container p-5">
    <form method="POST" novalidate> <!-- Change action="POST" to method="POST" -->
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object }}</p>
        <input type="submit" value="Confirm">
    </form>
</div>
{% endblock %}

core/templates/core/edit.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container p-5">
    <form method="POST" novalidate> <!-- Change action="POST" to method="POST" -->
        {% csrf_token %}
        {% for field in form.visible_fields %} <!-- Correct typo here -->
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %} <!-- Correct typo here -->
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}

        <div class="form-group">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span> Edit
            </button>
            <a class="btn btn-default" href="{% url 'core:post' %}">Cancel</a> <!-- Make sure this URL name is correct -->
        </div>
    </form>
</div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}

<div class="album py-5 bg-darkt">
    <div class="container">
        <div class="row">
            {% for core in index %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="" alt="images">
                    <div class="card-body">
                        <h4 class="">
                            <a href="{{core.get_absolute_url}}">{{core.title}}</a>
                        </h4>
                        <p class="card-text">Goes here</p>
                        <div class="d-flex justify-content-between align-item-center">
                            <div class="">
                                <small class="text-muted">9 minutes</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}

        </div>
    </div>
</div>

{% endblock %}

core/templates/core/navbar.html
<nav class="nav bg-dark p-3">
    <a class="nav-link active" href="/">Active</a>
    <a class="nav-link" href="#"></a>
    <a class="nav-link" href="{% url 'core:post' %}">Post</a>
    <a class="nav-link disabled">Disabled</a>
  </nav>

core/templates/core/posts.html
{% extends 'core/base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Post Administration</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:add' %}">Add new</a>
      </li>   
    </ul>
  </div>
</nav>

<div class="album py-5 bg-darkt">
    <div class="container">
        <div class="row">
            {% for post in post_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="" alt="images">
                    <div class="card-body">
                        <h4 class="">
                            <a href="{% url 'core:single' post.pk %}">{{post.title}}</a>
                        </h4>
                        <p class="card-text">Goes here</p>
                        <div class="d-flex justify-content-between align-item-center">
                            <div class="btn-group">
                              <a href="{{ post.get_absolute_url }}" class="btn btn-sm btn-primary" role="button">view</a>
                              <a href="{% url 'core:edit' post.pk %}" class="btn btn-sm btn-secondary p-2" role="button">edit</a>
                              <a href="{% url 'core:delete' post.pk %}" class="btn btn-sm btn-danger" role="button">delete</a>                              
                            </div>
                            <small class="text-muted">9 minutes</small>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}

        </div>
    </div>
</div>

{% endblock %}

core/templates/core/single.html
{% extends 'core/base.html' %}

{% block content %}

<div class="album py-5 bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="" alt="images">
                    <div class="card-body">
                        <h4 class="">
                            <h1>{{core.title}}</h1>
                        </h4>
                        <p class="card-text">Goes here</p>
                        <div class="d-flex justify-content-between align-item-center">
                            <div class="">
                                <small class="text-muted">9 minutes</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}